# Generated by Django 2.2.4 on 2019-11-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
