# Generated by Django 2.2.4 on 2019-11-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0002_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
