# Generated by Django 2.1.4 on 2019-11-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0002_calificacioncitamedica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacioncitamedica',
            name='doctor_id',
        ),
        migrations.DeleteModel(
            name='CalificacionCitaMedica',
        ),
    ]
