# Generated by Django 2.2.4 on 2020-01-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0002_info_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas_Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField()),
                ('m_url', models.CharField(max_length=300, null=True)),
                ('m_duration', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Doctor')),
            ],
        ),
    ]
