# Generated by Django 2.1.4 on 2020-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0002_info_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='static/imagenes/no-img.jpg', upload_to='static/imagenes')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='static/imagenes/no-img.jpg', upload_to='static/imagenes')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(max_length=250)),
            ],
        ),
    ]
