# Generated by Django 2.1.4 on 2020-01-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0003_consejos_noticias'),
        ('medicina', '0003_citas_medico'),
    ]

    operations = [
    ]
