# Generated by Django 2.2.4 on 2019-12-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0003_persona_pais'),
        ('medicina', '0003_auto_20191124_2105'),
    ]

    operations = [
    ]
