# Generated by Django 2.2.1 on 2019-12-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0003_persona_pais'),
        ('medicina', '0003_auto_20191124_2105'),
    ]

    operations = [
    ]
