# Generated by Django 2.2.4 on 2019-09-09 22:20

from django.db import migrations, models
import medicina.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0003_auto_20190909_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='https://via.placeholder.com/300x300', upload_to=medicina.models.imagen_up),
        ),
    ]
