# Generated by Django 2.2.4 on 2019-12-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0004_merge_20191204_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_consulta',
            name='consulta_id',
        ),
        migrations.AddField(
            model_name='consulta',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Detalle_Consulta'),
        ),
    ]
