# Generated by Django 2.2.4 on 2019-09-10 01:05

from django.db import migrations, models
import django.db.models.deletion
import medicina.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0004_persona_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='documento',
            field=models.FileField(null=True, upload_to=medicina.models.doc_up),
        ),
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(upload_to=medicina.models.imagen_up),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('dias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Dias')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Horario'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Examenes'),
        ),
    ]
