# Generated by Django 2.2.4 on 2020-01-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0004_merge_20200108_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='citas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
