# Generated by Django 2.2.4 on 2019-12-05 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0005_auto_20191204_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_consulta',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
