# Generated by Django 2.1.4 on 2019-12-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0004_merge_20191202_1318'),
        ('medicina', '0006_detalle_consulta_hora'),
    ]

    operations = [
    ]
