# Generated by Django 2.1.4 on 2019-09-10 20:40

from django.db import migrations, models
import medicina.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0006_auto_20190909_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(null=True, upload_to=medicina.models.imagen_up),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
