# Generated by Django 2.2.4 on 2019-12-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0006_detalle_consulta_hora'),
        ('medicina', '0004_merge_20191202_1318'),
    ]

    operations = [
    ]
