# Generated by Django 2.1.4 on 2019-10-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0007_auto_20190910_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEspecialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='matchespecialidades',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Doctor'),
        ),
        migrations.AddField(
            model_name='matchespecialidades',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Especialidad'),
        ),
    ]
