# Generated by Django 2.2.4 on 2019-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0007_merge_20191205_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='Telemedicina/static/images/no-img.jpg', upload_to='Telemedicina')),
                ('name', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('telefono', models.CharField(max_length=250, null=True)),
                ('ciudad', models.CharField(max_length=250, null=True)),
                ('direccion', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
