# Generated by Django 2.1.4 on 2019-12-05 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0008_grupo_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_familiar',
            name='usuario_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
