# Generated by Django 2.2.4 on 2020-01-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0008_paquete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.FloatField()),
                ('estado', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Doctor')),
            ],
        ),
    ]
