# Generated by Django 2.1.4 on 2019-12-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0008_publicidad'),
        ('medicina', '0009_auto_20191205_0254'),
    ]

    operations = [
    ]
