# Generated by Django 2.1.4 on 2020-01-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0009_pagos_doctor'),
        ('medicina', '0009_auto_20200109_0104'),
    ]

    operations = [
    ]
