# Generated by Django 2.2.4 on 2019-11-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0011_doctor_calificacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='citas_realizadas',
            field=models.IntegerField(default=0),
        ),
    ]
