# Generated by Django 2.2.4 on 2020-01-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0011_paquete_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_consulta',
            name='zoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Citas_Medico'),
        ),
    ]
