# Generated by Django 2.2.4 on 2019-11-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0012_doctor_citas_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='calificacion_total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='citas_realizadas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
