# Generated by Django 2.1.4 on 2020-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0012_detalle_consulta_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_medica',
            name='talla',
            field=models.FloatField(null=True),
        ),
    ]
