# Generated by Django 2.2.4 on 2020-01-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0013_doctor_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas_medico',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
