# Generated by Django 2.1.4 on 2020-01-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0014_auto_20200112_1249'),
        ('medicina', '0014_citas_medico_disponible'),
    ]

    operations = [
    ]
