# Generated by Django 2.2.4 on 2019-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0014_pagos_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos_paciente',
            name='pago_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
