# Generated by Django 2.2.4 on 2019-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0015_auto_20191116_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='citas_realizadas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
