# Generated by Django 2.2.4 on 2020-01-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0015_merge_20200114_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial_consulta',
        ),
    ]
