# Generated by Django 2.2.1 on 2020-01-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0015_merge_20200112_1516'),
        ('medicina', '0016_delete_historial_consulta'),
        ('medicina', '0015_merge_20200112_1331'),
    ]

    operations = [
    ]
