# Generated by Django 2.2.4 on 2019-11-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0016_paciente_citas_realizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_total', models.FloatField(default=0, null=True)),
                ('total_doctor', models.IntegerField(default=0, null=True)),
                ('citas_realizadas', models.IntegerField(default=0, null=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Especialidad')),
            ],
        ),
    ]
