# Generated by Django 2.2.4 on 2019-11-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0017_detalles_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_consulta',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Especialidad'),
        ),
    ]
