# Generated by Django 2.1.4 on 2020-01-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0017_merge_20200118_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_medica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Paciente'),
        ),
    ]
