# Generated by Django 2.1.4 on 2020-01-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0018_info_medica_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junta_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('estado_solicitud', models.IntegerField(default=0)),
                ('doctor_solicitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_solicitado', to='medicina.Doctor')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='medicina.Doctor')),
            ],
        ),
    ]
