# Generated by Django 2.1.4 on 2020-01-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0019_junta_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta_medica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Paciente'),
        ),
    ]
