# Generated by Django 2.2.4 on 2019-11-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0019_matchpaquetes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Paquetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_total', models.FloatField(default=0, null=True)),
                ('total_pacientes', models.IntegerField(default=0, null=True)),
                ('paquetes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Paquete')),
            ],
        ),
    ]
