# Generated by Django 2.2.4 on 2019-11-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0020_detalles_paquetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpaquetes',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='matchpaquetes',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicina.Paquete'),
        ),
    ]
